batch_size: 128
# batch_size: 16384
layers: [5,20, 20, 20, 1]
#layers: [5, 150, 150, 150, 150, 1]
epochs: 10
#data_run: ["05-05", "09-01", "025-075"]
plots: [extrapolation, data-distribution, tensorboard, extrapolation_wave, movie]
lr: 1.0e-4
#data_run: fine_mesh_gauss_few/20210727-093118
#data_run: 05-05
data_run: [05-05, 09-01, 025-075]
from_tensor_slices: true
source: wave_with_source
test_source: [0.6, 0.6]
activation: elu
test_data_dir: data/wave/06-06/