batch_size: 512
# batch_size: 16384
# layers: [3,20, 20, 20, 1]
layers: [3, 100, 100, 100, 100, 100, 1]
lr: 5.0e-5
grad_reg_const: .1
gradient_loss: second_explicit
epochs: 10000

be_greedy: true

from_tensor_slices: false