batch_size: 4096
# batch_size: 16384
# layers: [3,20, 20, 20, 1]
layers: [5, 10, 10, 10, 1]
epochs: 10
data_run: ["05-05", "09-01", "025-075"]
plots: [extrapolation, data-distribution, tensorboard, extrapolation_wave]