<<<<<<< HEAD
gradient_loss: true
epochs: 1000
dropout_rates: [0.2, 0.0, 0.0]
=======
activation: tanh
debug: false
epochs: 15000
num_data: 2500
lr: 1.0e-4
>>>>>>> 02a01f0fb89b442d3f8b4aeaaeda22bd53dcde75
