batch_size: 512
# batch_size: 16384
# layers: [3,20, 20, 20, 1]
layers: [3, 150, 150, 150, 150, 1]
lr: 1.0e-4
grad_reg_const: 50
activation: tanh
gradient_loss: second_explicit
epochs: 500

from_tensor_slices: true