batch_size: 512
layers: [3, 100, 100, 100, 100, 100, 3]
lr: 1.0e-3
grad_reg_const: 0.0001    # !!!
activation: tanh
model_outputs: all
gradient_loss: 
  wave_eq: [first_explicit]
  boundary: [velocity]
epochs: 5000

lr_scheduler: true
lr_scheduler_type: polynomial_decay
lr_scheduler_params: [1.0e-3, 3.0e-5, 10, 1.0] #[initial, final, decay_steps, power]
lr_scheduler_type: piecewise_linear
lr_scheduler_params: [1.0e-3, 1.0e-4, 10, 20] #[initial, final, start_epoch, end_epoch]

loss_schedulerizer: true
loss_schedulerizer_params: [500, 1000] #[Begin adding grad, fully added]

# false -> slow graph, fast epoch
# true -> fast graph, slower epoch
from_tensor_slices: false
shuffle: true # Shuffles at the start of each epoch

# turns on eagerly mode
debug: false
