lr_scheduler: true
lr_scheduler_type: piecewise_linear
lr_scheduler_params: [1.0e-3, 1.0e-4, 700, 1000] #[initial, final, decay_steps, power]

loss_schedulerizer: false
loss_schedulerizer_params: [400, 700] #[Begin adding grad, fully added]