#source: wave_with_source
source: wave

batch_size: 512
layers: [3, 100, 100, 100, 100, 100, 3]
grad_reg_const: 0.05    # !!!
activation: tanh
model_outputs: all

epochs: 2000

gradient_loss: 
  - region: boundary_lr     # which data to apply to
    name: velocity_lr       # id of gradient regularizer
    weight: [0.0, 0.03]     # start_weight, end_weight
    schedule: [200, 500]    # start_epoch,  end_epoch
  - region: boundary_ud   
    name: velocity_ud     
    weight: [0.0, 0.03]    
    schedule: [200, 500]  
  - region: interior
    name: first_explicit     
    weight: [0.0, 0.03]    
    schedule: [500, 1000]  
  - region: interior
    name: second_explicit     
    weight: [0.0, 0.001]    
    schedule: [1100, 1400]  
  - region: interior
    name: second_curl     
    weight: [0.0, 0.001]    
    schedule: [1500, 1800] 

lr: 1.0e-3
lr_scheduler: true
#lr_scheduler_type: polynomial_decay
#lr_scheduler_params: [1.0e-3, 3.0e-5, 10, 1.0] #[initial, final, decay_steps, power]
lr_scheduler_type: piecewise_linear
lr_scheduler_params: [1.0e-3, 5.0e-5, 400, 1800] #[initial, final, start_epoch, end_epoch]

data_run: [source_point_130] 
data_sources: [[0.5, 0.5]]

test_source: [0.5, 0.5]
test_data_dir: source_point_130

# false -> slow graph, fast epoch
# true -> fast graph, slower epoch
from_tensor_slices: true 
shuffle: true # Shuffles at the start of each epoch

# turns on eagerly mode
debug: false

