###########
#  Model  #
###########
activation: tanh
dropout_rates: 0.0
layers: [3, 20, 20, 20, 1]

##############
#  Training  #
##############
device: gpu
trials: 1
seed: 0
epochs: 12000
batch_size: 256
lr: 1.0e-4
lr_scheduler: false
lr_scheduler_params: [1.0e-3, 1.0e-6, 2500, 1.0] #[initial, final, decay_steps, power]
gd_noise: 0.0

#############
#  Dataset  #
#############
#source: wave_with_source
source: wave
data_dir: data/wave/
data_run: '' #Leave blank to default to last run in data_sir folder

corners: false
dataset: [2500, 7500, 0, 1.0, 0.0] #[interior, exterior, border, labeled_int%, labeled_ext%]
noise: 0.0

from_tensor_slices: true

data_sources: [[0.5, 0.5], [0.9, 0.1], [0.25, 0.75]]
test_source: [0.6, 0.6]
test_data_dir: data/wave/06-06/

##################
#  Regularizers  #
##################
regularizer: none
reg_const: 0.1
# none, const, zero, first
gradient_loss: none
#grad_reg_norm: l1 l2
grad_reg_const: 1

#############
#  Logging  #
#############
debug: false
output_dir: null   # overridden in main.py
output_root: output/wave
plots: [extrapolation, data-distribution, tensorboard, extrapolation_wave, heatmap, movie]
saves: [model]
