###########
#  Model  #
###########
activation: elu
dropout_rates: 0.0
layers: [3, 20, 20, 20, 1]

##############
#  Training  #
##############
device: gpu
trials: 1
seed: 0
epochs: 12000
batch_size: 256
lr: 1.0e-4
lr_scheduler: false
lr_scheduler_params: [1.0e-3, 1.0e-6, 2500, 1.0] #[initial, final, decay_steps, power]
gd_noise: 0.0

#############
#  Dataset  #
#############
source: wave
data_dir: data/wave/
data_run: '' # Leave blank to default to first run in data_dir

corners: false
dataset: [2500, 7500, 0, 1.0, 0.0] #[interior, exterior, border, labeled_int%, labeled_ext%]
noise: 0.0

##################
#  Regularizers  #
##################
regularizer: none
reg_const: 0.1
# none, const, zero, first
gradient_loss: none
#grad_reg_norm: l1 l2
grad_reg_const: 1

#############
#  Logging  #
#############
debug: false
output_dir: null   # overridden in main.py
output_root: output/wave
plots: [extrapolation, data-distribution, tensorboard, extrapolation_wave, heatmap]
saves: [model]
