###########
#  Model  #
###########
activation: elu
layers: [2, 20, 20, 20, 1]

##############
#  Training  #
##############
runs: 5
seed: 0
epochs: 5000
batch_size: 256
lr: 1.0e-4
lr_scheduler: false
lr_scheduler_params: [1.0e-3, 1.0e-6, 2500, 1.0] #[initial, final, decay_steps, power]

#############
#  Dataset  #
#############
output_dir: null   # overridden in main.py
target_coefficients: [1.0, 1.0]
target: parabola
corners: false
dataset: [2500, 0, 7500, 1.0, 0.0] #[interior, exterior, border, labeled_int%, labeled_ext%]
noise: 0.0

##################
#  Regularizers  #
##################
regularizer: none
reg_const: 0.1
# none, const, zero, first
gradient_loss: zero
#grad_reg_norm: l1 l2
grad_reg_const: 1

#############
#  Logging  #
#############
debug: false

dropout_rates: [0.0, 0.0, 0.0]
plots: [extrapolation, data-distribution, tensorboard]
saves: []
