output_dir: output/no_exp_id
lr: 1.0e-4
activation: elu
layers: [2, 20, 20, 20, 1]
epochs: 1000
batch_size: 256
num_data: 10000
plots: true
gradient_loss: false
f_a: 1.0
f_b: 1.0
regularizer: none
reg_const: 0.1
debug: false
detailed_save: true
corners: false
dataset: [.9, .1, 1.0, 1.0] #[interior%, exterior%, labeled_int%, labeled_ext%]
lr_scheduler: false
lr_scheduler_params: [1.0e-3, 1.0e-6, 2500, 1.0]
