###########
#  Model  #
###########
activation: elu
layers: [2, 20, 20, 20, 1]

##############
#  Training  #
##############
runs: 5
seed: 0
epochs: 1000
batch_size: 256
lr: 1.0e-4
lr_scheduler: false
lr_scheduler_params: [1.0e-3, 1.0e-6, 2500, 1.0] #[initial, final, decay_steps, power]

#############
#  Dataset  #
#############
output_dir: null   # overridden in main.py
f_a: 1.0
f_b: 1.0
target: parabola
corners: false
dataset: [1000, 0, 3000, 1.0, 0.0] #[interior, exterior, border, labeled_int%, labeled_ext%]
noise: 0.01

##################
#  Regularizers  #
##################
regularizer: none
reg_const: 0.1
gradient_loss: const
#grad_reg_norm: l1 l2
grad_reg_const: 1

#############
#  Logging  #
#############
debug: false
plots: [extrapolation, data-distribution, tensorboard]
saves: [model]