output_dir: output/no_exp_id
lr: 1.0e-4
activation: tanh
layers: [2, 20, 20, 20, 1]
epochs: 1000
batch_size: 256
num_data: 10000
plots: true
gradient_loss: false
f_a: 1.0
f_b: 1.0
regularizer: none
reg_const: 0.1

# Not Implemented yet
corners: false
dataset: [.2, .5, .3]
lr_scheduler: exp-decay
ext-data: .1